name: checkups
description: "Applicazione CheckUps per la gestione di "
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  riverpod: ^2.4.10
  flutter_riverpod: ^2.4.10  
  sqflite: ^2.3.2
  path: ^1.8.3
  path_provider: ^2.1.2
  pdf: ^3.10.8
  intl: ^0.19.0
  json_annotation: ^4.8.1
  uuid: ^4.3.3
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.1.2
  data_table_2: ^2.5.10
  file_picker: ^10.1.9
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  isar_generator: ^3.1.0

  json_serializable: ^6.7.1

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/logo/
    - assets/fonts/


  fonts:
    - family: Arial
      fonts:
        - asset: assets/fonts/arial/ARIAL.TTF
          weight: 400
        - asset: assets/fonts/arial/ARIALBD.TTF
          weight: 700
        - asset: assets/fonts/arial/ARIALI.TTF
          style: italic
        - asset: assets/fonts/arial/ARIALBI.TTF
          weight: 700
          style: italic
        - asset: assets/fonts/arial/ARIBLK.TTF
          weight: 900
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica-Bold-Font.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
    